import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import React from "react";
import Header from "@/components/Header/header";

const aspekta = localFont({
    src: [
        {
            path: '../public/fonts/Aspekta-100.woff2',
            weight: '100',
            style: 'extralight',
        },
        {
            path: '../public/fonts/Aspekta-250.woff2',
            weight: '250',
            style: 'thin',
        },
        {
            path: '../public/fonts/Aspekta-400.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../public/fonts/Aspekta-700.woff2',
            weight: '700',
            style: 'bold',
        },
    ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aspekta.className} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
